[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "About Me"
    name = "About Me"
    url = "https://fwd2cv.com/"
    weight = 2

[[main]]
    identifier = "work"
    name = "Work 2"
    url = "/work/"
    weight = 3

[[main]]
    identifier = "Socials"
    name = "Socials"
    url = "https://links.fwd2cv.com/"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 5

[[main]]
    identifier = "Support"
    name = "Support"
    url = "https://buymeacoffee.com/cvandusen"
    weight = 6
    
# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://x.com/FWD2CV"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/fwd2cv/"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Cvanduse"
    weight = 3